version: '3.8'

services:

  mlflow-ui:
    build: . 
    command: mlflow ui --backend-store-uri sqlite:///mlruns.db --host 0.0.0.0
    ports:
      - "5000:5000" 
    volumes:
      - ./:/app 

  api:
    build: . 
    command: uvicorn src.serve_model:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - mlflow-ui 
    volumes:
      - ./:/app 
